/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class one_JNIExample */

#ifndef _Included_one_JNIExample
#define _Included_one_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     one_JNIExample
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_one_JNIExample_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     one_JNIExample
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_one_JNIExample_helloWorld
  (JNIEnv *, jobject);

/*
 * Class:     one_JNIExample
 * Method:    getMsg
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_one_JNIExample_getMsg
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
